const COLLECTION = "disbursement_response";

const ATTRIBUTE_ACCOUNT_NUMBER = "account_number";
const ATTRIBUTE_AMOUNT = "amount";
const ATTRIBUTE_BANK_CODE = "bank_code";
const ATTRIBUTE_BENEFICIARY_NAME = "beneficiary_name";
const ATTRIBUTE_DATA = "data";
const ATTRIBUTE_FEE = "fee";
const ATTRIBUTE_ID = "id";
const ATTRIBUTE_RECEIPT = "receipt";
const ATTRIBUTE_REMARK = "remark";
const ATTRIBUTE_RESPONSE_STATUS = "status";
const ATTRIBUTE_RESPONSE_STATUS_TEXT = "status_text";
const ATTRIBUTE_STATUS = "status";
const ATTRIBUTE_TIME_SERVED = "time_served";
const ATTRIBUTE_TIMESTAMP = "timestamp";

export default Object.freeze({
  ATTRIBUTE_ACCOUNT_NUMBER,
  ATTRIBUTE_AMOUNT,
  ATTRIBUTE_BANK_CODE,
  ATTRIBUTE_BENEFICIARY_NAME,
  ATTRIBUTE_DATA,
  ATTRIBUTE_FEE,
  ATTRIBUTE_ID,
  ATTRIBUTE_RECEIPT,
  ATTRIBUTE_REMARK,
  ATTRIBUTE_RESPONSE_STATUS_TEXT,
  ATTRIBUTE_RESPONSE_STATUS,
  ATTRIBUTE_STATUS,
  ATTRIBUTE_TIME_SERVED,
  ATTRIBUTE_TIMESTAMP,

  COLLECTION,
});
