const ATTRIBUTE_ID = "id";
const ATTRIBUTE_AMOUNT = "amount";
const ATTRIBUTE_STATUS = "status";
const ATTRIBUTE_TIMESTAMP = "timestamp";
const ATTRIBUTE_BANK_CODE = "bank_code";
const ATTRIBUTE_ACCOUNT_NUMBER = "account_number";
const ATTRIBUTE_BENEFICIARY_NAME = "beneficiary_name";
const ATTRIBUTE_REMARK = "remark";
const ATTRIBUTE_RECEIPT = "receipt";
const ATTRIBUTE_TIME_SERVED = "time_served";
const ATTRIBUTE_FEE = "fee";

export default Object.freeze({
  ATTRIBUTE_ID,
  ATTRIBUTE_AMOUNT,
  ATTRIBUTE_STATUS,
  ATTRIBUTE_TIMESTAMP,
  ATTRIBUTE_BANK_CODE,
  ATTRIBUTE_ACCOUNT_NUMBER,
  ATTRIBUTE_BENEFICIARY_NAME,
  ATTRIBUTE_REMARK,
  ATTRIBUTE_RECEIPT,
  ATTRIBUTE_TIME_SERVED,
  ATTRIBUTE_FEE,
});
