const ATTRIBUTE_ACCOUNT_NUMBER = "account_number";
const ATTRIBUTE_AMOUNT = "amount";
const ATTRIBUTE_BANK_CODE = "bank_code";
const ATTRIBUTE_REMARK = "remark";

const FIELD_HEADER_CONTENT_TYPE = "Content-Type";
const FIELD_HEADER_AUTHORIZATION = "Authorization";

export default Object.freeze({
  ATTRIBUTE_ACCOUNT_NUMBER,
  ATTRIBUTE_AMOUNT,
  ATTRIBUTE_BANK_CODE,
  ATTRIBUTE_REMARK,

  FIELD_HEADER_CONTENT_TYPE,
  FIELD_HEADER_AUTHORIZATION,
});
